### PR TITLE
#162342397 Create article expression model

### PR DESCRIPTION
**Pull request by theghostyced**
#### What does this PR do?
Create an article expression model for the project
#### Description of Task to be completed?
- Create Article Expression File
- Adds the following fields to the model
```
 articleExpression{
  id int PK
  articleId int
  userId int
  emotion varchar
  created_at date
  update_at date
}
```
- Adds relationship between the model and Articles model
- Adds relationship between the model and Users model
#### How should this be manually tested?
Clone the project and check the `models` folder for the `articleExpression` file.
#### Any background context you want to provide?
*N/A*
#### What are the relevant pivotal tracker stories?
[#162342397](https://www.pivotaltracker.com/story/show/162342397)
#### Screenshots (if appropriate)
*N/A*
#### Questions:
*N/A*

### CODE REVIEW

**Comment by ekpangmichael** [comment]
Awesome job, I think you have a typo on your spelling of foreignKey.

**Comment by theghostyced** [comment]
Thanks @ekpangmichael. Fixed

**Review by Danielshow — APPROVED** [review]
Looks good to me. Nice work @theghostyced

@efalayi

**Comment by V-84** [comment]
nice work Daniel, looks good to me

**Pull request merged**
